name: RefMapDashboard
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.3
  - ld_impl_linux-64=2.44
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.19
  - packaging=25.0
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.12.12
  - readline=8.3
  - setuptools=80.10.1
  - sqlite=3.51.1
  - tk=8.6.15
  - tzdata=2025c
  - wheel=0.46.3
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - blinker==1.9.0
      - cartopy==0.25.0
      - certifi==2026.1.4
      - cftime==1.6.5
      - click==8.3.1
      - cloudpickle==3.1.2
      - contourpy==1.3.3
      - cycler==0.12.1
      - dask==2026.1.2
      - flask==3.1.2
      - flask-cors==6.0.2
      - fonttools==4.61.1
      - fsspec==2026.1.0
      - geopandas==1.1.2
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - locket==1.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - netcdf4==1.7.4
      - numpy==2.4.2
      - pandas==3.0.0
      - partd==1.4.2
      - pillow==12.1.0
      - pyogrio==0.12.1
      - pyparsing==3.3.2
      - pyproj==3.7.2
      - pyshp==3.0.3
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - scipy==1.17.0
      - shapely==2.1.2
      - six==1.17.0
      - toolz==1.1.0
      - tqdm==4.67.2
      - trimesh==4.11.1
      - werkzeug==3.1.5
      - xarray==2026.1.0
prefix: /tools/miniconda3/envs/RefMapDashboard
