apiVersion: apps/v1
kind: Deployment
metadata:
  name: emissions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emissions
  template:
    metadata:
      labels:
        app: emissions
    spec:
      containers:
      - name: emissions
        image: refmap/emissions:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4005
        volumeMounts:
        - name: data-volume
          mountPath: /app/data
      volumes:
      - name: data-volume
        hostPath:
          path: /refmap_dashboard/backend/emissions/data
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: emissions
spec:
  type: NodePort
  selector:
    app: emissions
  ports:
    - protocol: TCP
      port: 4005
      targetPort: 4005
      nodePort: 30005
